### ISSUE TITLE
React/NextJS - SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by DilwoarH** [thoughtspot/visual-embed-sdk#839]
Hey,

Not sure if this has been flagged, but the build keeps failing because of the following error.

**NextJS version 13.1.2**
**@thoughtspot/visual-embed-sdk version 1.18.0**

You can view a live demo [here](https://codesandbox.io/p/sandbox/ecstatic-cartwright-ggjpcr?file=%2Fpages%2Findex.tsx).

Command run:
```bash
npm run build
```

Result:
```js
import { AppEmbed, Page } from './embed/app';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Object.compileFunction (node:vm:352:18)
    at wrapSafe (node:internal/modules/cjs/loader:1031:15)
    at Module._compile (node:internal/modules/cjs/loader:1065:27)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.6094 (/Users/█████/.next/server/pages/ts-report-prototype.js:27:42)
    at __webpack_require__ (/Users/█████/.next/server/webpack-runtime.js:25:42)

> Build error occurred
```

Code:
```jsx
import { init, LiveboardEmbed, AuthType } from "@thoughtspot/visual-embed-sdk"
import { useEffect } from "react"

export default function ThoughtSpotReportPrototype() {
  useEffect(() => {
    try {
      init({
        thoughtSpotHost: "https://my2.thoughtspot.cloud",
        authType: AuthType.None,
      })

      const embed = new LiveboardEmbed("#embed", {
        frameParams: {},
        fullHeight: true,
        liveboardId: "█████",
      })

      embed.render()
    } catch (error) {
      console.error(error)
    }
  })

  return (
    <div>
        <h1 className="p-7 mt-5 text-3xl font-bold underline">
          ThoughtSpot Report Prototype
        </h1>
        <div id="embed" className="mt-5"></div>
     </div>
  )
}

```

**Comment by DilwoarH** [comment]
This can be closed as it seems that we need to use [Dynamic importing](https://nextjs.org/docs/advanced-features/dynamic-import) to avoid this issue from happening.

**Solution**:
Create a separate component then import it into page view via a dynamic import with SSR turned off.

```jsx
import dynamic from 'next/dynamic'

const SomeThoughtSpotReport = dynamic(() => import('../components/SomeThoughtSpotReport'), {
  ssr: false,
})
```

Here is an example of it working: https://codesandbox.io/p/sandbox/thoughtspot-prototype-forked-7mrhm7

**Comment by ashubham** [comment]
Thanks @DilwoarH
